### PR TITLE
Import bl-reload-gtk23 and bl-xinerama-prop from bl-utilities with history

### PR DESCRIPTION
**Pull request by ghost**
As discussed, import the named tools and all pending changes from https://github.com/BunsenLabs/bunsen-utilities/pull/68 into here.

### CODE REVIEW

**Review by johnraff — COMMENTED** [review]
bl-reload-gtk23 might need some attention before shipping.
It seemed to have no effect on GTK2 apps after editing ~/.gtkrc-2.0, as compared with changing a theme in lxappearance. Installing and providing a config file for xsettingsd introduced some error messages.

bl-xinerama-prop worked fine.

Both scripts produced clean help messages which should support auto manpage generation OK.

The extra python dependencies for bunsen-common were something I had forgotten to consider. As a core dependency of other BL packages it should be as light as possible. However, the total extra installed size of 2~3MB is perhaps acceptable?

**Comment by ghost** [comment]
^ The way I tested GTK2 and bl-reload-gtk23:

 * My personal preference would have been to leave the tools in bl-utilities. Keeping all executables together. 
 * I have KDE normally. So I used KWIN.
 * I copied ~/.gtkrc-2.0 to /tmp
 * I launched GTK2 applications using `env GTK2_RC_FILES=/path/to/the/copied/gtk2rc` application`
 * I then edited the file at GTK2_RC_FILES, saved and ran the tool; it notified the application correctly. Retested now without setting this environment variable, also worked fine.
 * This also worked correctly when testing using BLOB and the latest lithium dev ISO (=> changed theme correctly applied). Wonder what's different on your end.
 * Could you please run bl-reload-gtk23 with the -d switch and post the output here, it's the debug output. That'd be useful. 
 * Could you open a window using ` xev`? When running the tool, the window will show a ClientMessage event in the output immediately when the window is notified correctly.
 * Please also post the xsettingsd error messages. In any case, the errors would be coming from xsettingsd not bl-reload-gtk23 I think? Here, I'd also need full (debug) output. gtk23 only sends a signal to xsettingsd.

**Comment by johnraff** [comment]
> My personal preference would have been to leave the tools in bl-utilities. Keeping all executables together.

OK, also considering the extra python dependencies they would bring to bunsen-common, let's keep these two tools in **bunsen-utilities** after all. 

My reasoning was the purely hypothetical idea that some future developer writing a script in some other BL package might want to use such generic tools, without having to depend on the rather big bunsen-utilities. But bunsen-common is something nearly every BL package depends on, so should be as small and light as possible.

--
Anyway, now doing some more testing of bl-reload-gtk23.
For now, since GTK3 would be an enhancement over what we have now anyway, I'm going to uninstall xsettingsd and focus on GTK2.

**Comment by johnraff** [comment]
Let's close this PR here on bunsen-common, and continue the discussion of bl-reload-gtk23 on bunsen-utilities.

**Pull request closed without merging**
